In [1]:
%store -r X
%store -r y
%store -r X_test
%store -r y_test
%store -r feature_names

In [2]:
# Import thư viện
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [3]:
import matplotlib.pyplot as plt

# Reshape data
X_2d = X.reshape(-1, X.shape[-1])
y_reshaped = np.repeat(y, 20)

In [4]:
# Khởi tạo mô hình Random Forest
model = RandomForestClassifier(n_estimators=500)

In [5]:
# Huấn luyện mô hình
model.fit(X_2d, y_reshaped)

RandomForestClassifier(n_estimators=500)

In [6]:
# Lấy tầm quan trọng của đặc trưng
feature_importances = model.feature_importances_

# In tầm quan trọng của đặc trưng
print(feature_importances)

[0.01692461 0.01344813 0.01304505 0.01277987 0.01304292 0.01306466
 0.01307065 0.01299117 0.01285219 0.01319563 0.01297639 0.01243269
 0.01998636 0.02946261 0.03384276 0.03069419 0.02533724 0.0340518
 0.02418257 0.02539316 0.01537142 0.01945214 0.01628112 0.01874769
 0.01534013 0.01411441 0.01430616 0.0172292  0.01202892 0.00950474
 0.00821977 0.00536496 0.00508597 0.00466294 0.00532115 0.00496262
 0.00447601 0.00430219 0.00443992 0.0052605  0.0046718  0.00410294
 0.00519004 0.00483839 0.00482238 0.0039002  0.00450475 0.00453442
 0.00405898 0.00502258 0.00432093 0.00462777 0.0058081  0.00568193
 0.00511967 0.00482674 0.00516437 0.00703925 0.00539126 0.0054483
 0.00811297 0.00737216 0.00669306 0.00620411 0.00472294 0.00468358
 0.00463122 0.00473541 0.0049283  0.00440636 0.00490365 0.00470958
 0.00472793 0.00534825 0.00526514 0.00423776 0.00419696 0.00439483
 0.00552883 0.00594816 0.00546342 0.00522615 0.00514794 0.00530958
 0.00481223 0.0048921  0.00374365 0.00400373 0.00351265 0.003704

In [7]:
feature_importances.shape

(128,)

In [8]:
# Tạo dataframe gồm tên đặc trưng và tầm quan trọng
feature_importances_df = pd.DataFrame({"feature_name": feature_names, "importance": feature_importances})

# Sắp xếp dataframe theo tầm quan trọng
feature_importances_df = feature_importances_df.sort_values("importance", ascending=False)

# Lấy index của dataframe
indices = feature_importances_df.index

# In index
print(indices)

Index([ 17,  14,  15,  13,  19,  16,  18,  12,  21,  23,
       ...
       112,  96,  86,  89, 115, 114, 104, 106, 107,  88],
      dtype='int64', length=128)


In [9]:
k = 64
top_k_indices = indices[:k]

In [10]:
selected_X = X[:,:,top_k_indices]
selected_X_test = X_test[:,:,top_k_indices]

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Khởi tạo mô hình
model = keras.Sequential()

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(20, k, 1), padding='same'))

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5,5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(layers.Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(layers.Dense(64, activation='relu'))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp fully connected (Dense Layer) cuối cùng với số lớp đầu ra phụ thuộc vào bài toán của bạn
model.add(layers.Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()

# Biên dịch mô hình
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 20, 64, 32)     │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 20, 64, 32)     │        25,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 10, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 10, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 10, 32, 64)     │        51,264 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 10, 32, 64)     │       102,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 16, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 5120)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       327,744 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │           325 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 508,261 (1.94 MB)

 Trainable params: 508,261 (1.94 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.fit(selected_X, y, epochs=10, batch_size=16)

Epoch 1/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 48s 58ms/step - accuracy: 0.4861 - loss: 1.2023
Epoch 2/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 46s 56ms/step - accuracy: 0.8014 - loss: 0.5299
Epoch 3/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 41s 50ms/step - accuracy: 0.8529 - loss: 0.4083
Epoch 4/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 41s 50ms/step - accuracy: 0.8594 - loss: 0.3911
Epoch 5/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 48s 58ms/step - accuracy: 0.8809 - loss: 0.3315
Epoch 6/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 41s 50ms/step - accuracy: 0.8787 - loss: 0.3328
Epoch 7/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 39s 47ms/step - accuracy: 0.8931 - loss: 0.3010
Epoch 8/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 47s 57ms/step - accuracy: 0.8989 - loss: 0.2925
Epoch 9/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 47s 56ms/step - accuracy: 0.9081 - loss: 0.2660
Epoch 10/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 51s 62ms/step - accuracy: 0.9004 - loss: 0.2719


In [13]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(selected_X_test, y_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(selected_X_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)

412/412 ━━━━━━━━━━━━━━━━━━━━ 11s 26ms/step - accuracy: 0.9384 - loss: 0.1689
Độ chính xác trên tập kiểm tra: 0.9270089864730835
412/412 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   0 1986    4   11   33]
 [   0   43 2436    3  326]
 [   0  341    7 1386    6]
 [   0   32  155    0 3555]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.83      0.98      0.90      2034
           2       0.94      0.87      0.90      2808
           3       0.99      0.80      0.88      1740
           4       0.91      0.95      0.93      3742

    accuracy                           0.93     13166
   macro avg       0.93      0.92      0.92     13166
weighted avg       0.93      0.93      0.93     13166

